{% set name = "apache-airflow-providers-datadog" %}
{% set version = "3.9.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_datadog-{{ version }}.tar.gz
  sha256: c676104424054e91820f00f47f1199131ee6a5fe5c36b6be5ecaada7ccbd34f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - apache-airflow-providers-common-compat >=1.8.0
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - datadog >=0.50.0

test:
  imports:
    - airflow.providers.datadog
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-datadog for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/datadog/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-datadog/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
